### config.toml
title = "OpenPOWER Foundation"
baseURL = "https://openpowerfoundation.org/"
theme = "openpowerfoundation"
#languageCode = "opf"
#defaultContentLanguage = "opf"
#defaultContentLanguageInSubdir = true
#enableMissingTranslationPlaceholders = true
dataDir = "data"
assetDir = "assets"
PaginatePath = ""
sectionPagesMenu = "main"
buildDrafts = false
pygmentsUseClasses = true
enableGitInfo = true
enableRobotsTXT = true
disableHugoGeneratorInject = false
enableInlineShortcodes = true
enableEmoji = true

[build]
	noJSConfigInAssets = false
#	useResourceCacheWhen = 'always'
	writeStats = true
	[build.buildStats]
		enable = true
		disableClasses = false
		disableIDs = false
		disableTags = false
	[[build.cacheBusters]]
		source = '(postcss|tailwind)\.config\.js'
		target = '(css|styles|scss|sass)'

[outputs]
	home = [ "HTML" , "RSS" ]
	section = [ "HTML", "RSS" ]
	page = [ "HTML" , "RSS" , "JSON" , "LDIF" ]
	taxonomy = [ "HTML" , "JSON" , "RSS" ]
#	term = [ "HTML" , "JSON" ]

[outputFormats]
[outputFormats.RSS]
	mediatype = "application/rss"
	baseName = "feed"
	suffix = "xml"
	isPlainText = false
	notAlternative = false
[outputFormats.JSON]
	mediaType = "application/json"
	baseName = "index"
	suffix = "json"
	isPlainText = false
	notAlternative = true
[outputFormats.LDIF]
	name = "ldif"
	mediaType = "text/ldif"
	baseName = "index"
	suffix = "ldif"
	isPlainText = false
	notAlternative = true

[mediaTypes]
[mediaTypes."text/ldif"]
	suffixes = [ "ldif" ]

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
	definitionList = true
	footnote = true
	linkify = true
	strikethrough = true
	table = true
	taskList = true
	typographer = true
[markup.goldmark.parser]
	autoHeadingID = true
	autoHeadingIDType = 'github'
[markup.goldmark.parser.attribute]
	block = false
	title = true
[markup.goldmark.renderer]
	hardWraps = false
	unsafe = true
	xHTML = true
[markup.highlight]
	codeFences = true
	lineNos = true
	lineNumbersInTable = true
	noClasses = false
[markup.tableOfContents]
	endLevel = 4
	ordered = false
	startLevel = 2

[imaging]
	resampleFilter = "MitchellNetravali"
	quality = 100
	anchor = "smart"
	bgColor = "#ffffff"
[imaging.exif]
	includeFields = ""
	excludeFields = ".*"
	disableDate = false
	disableLatLong = false

[sitemap]
	changefreq = "weekly"
	filename = "sitemap.xml"
	priority = 0.5

[taxonomies]
	tag = "tags"
	category = 'categories'
	series = 'series'

[minify]
	disableCSS = false
	disableHTML = false
	disableJS = false
	disableJSON = false
	disableSVG = false
	disableXML = false
	minifyOutput = true
[minify.tdewolff]
[minify.tdewolff.html]
	keepComments = false
	keepConditionalComments = false
	keepDefaultAttrVals = true
	keepDocumentTags = true
	keepEndTags = true
	keepQuotes = false
	keepWhitespace = false
[minify.tdewolff.css]
	keepWhitespace = false
	keepCSS2 = true
	precision = 0
[minify.tdewolff.js]
	keepVarNames = false
	precision = 0
[minify.tdewolff.json]
	keepNumbers = false
	precision = 0
[minify.tdewolff.svg]
	precision = 0
[minify.tdewolff.xml]
	keepWhitespace = false

[caches]
[caches.assets]
	dir = ':resourceDir/_gen'
	maxAge = -1
[caches.getresource]
	dir = ':cacheDir/:project'
	maxAge = -1
[caches.images]
	dir = ':resourceDir/_gen'
	maxAge = -1
[caches.modules]
	dir = ':cacheDir/modules'
	maxAge = -1
