#!parms.toml
# Analytics temporarily disabled while migrating away from vantosh.com hosting.
# [analytics.piwik]
# 	URI = "stats.vantosh.com"
# 	ID = "69"
[forms.contact]
	URI = "https://webscripts.vantosh.com/forms/contactus/opf"
[forms.hub]
	URI = "https://webscripts.vantosh.com/forms/hub/opf"
[forms.isarfc]
	URI = "https://webscripts.vantosh.com/forms/isarfc/opf"
[forms.passport]
	URI = "https://webscripts.vantosh.com/forms/passport/opf"
[forms.mailmonk]
	URI = "https://mailing.openpower.foundation/subscription/form"
